### ISSUE TITLE
Support for altering maximum travel speed

### ISSUE THREAD

**Issue by hifihedgehog** [fieldOfView/PrinterSettingsPlugin#13]
Could you adding maximum travel speed as another editable option? I need it since I cannot edit my printer’s configuration as Cura is installed as a snap and its application directory is immutable. This is the option I would need added:

https://community.ultimaker.com/topic/35297-travel-speed-limited-to-300mms/?do=findComment&comment=279463

**Comment by fieldOfView** [comment]
There is no setting named "Maximum Travel Speed" in Cura. There is a "Travel Speed" which is already editable, and it is (by default) limited to `math.sqrt(machine_max_feedrate_x ** 2 + machine_max_feedrate_y ** 2)`, or in other words the maximum speed that the printer definition says the printer can move. `machine_max_feedrate_x ` is the internal name for "Maximum Speed X", which my plugin already makes editable.

If Cura does not let you slice with a high travel speed, you have to increase both the "Maximum Speed X" and the "Maximum Speed Y" in the Printer Settings category.

**Comment by fieldOfView** [comment]
Oh, I see, the Voron definition sets a maximum value for the Travel Speed that does not rely on the "Maximum Speed X" and "... Y". That is not something this plugin can fix.

What you could do is not use the Voron definition, but use a Custom FFF printer instead.
