### ISSUE TITLE
Not compatible with cura V5

### ISSUE THREAD

**Issue by Festivejelly** [fieldOfView/PrinterSettingsPlugin#14]
This plugin doesnt seem to be compatible with cura version 5

**Comment by fieldOfView** [comment]
It is, if you use the latest version available in the Marketplace.

Can you be a little more specific about why you think it does not work? 
It would also be helpful if you posted a link to your cura.log (see Help -> Show configuration folder; the cura.log file is in the folder that opens).

**Comment by brucetony** [comment]
It does work in Cura 5. @Festivejelly You need to make sure you install the "Printer Settings" plugin from the marketplace, then enable visualization of settings in Preferences. By default, the Printer Settings this plugin adds are not readily accessible (like many other settings in Cura), you have to toggle them to be visible, or search for keywords (e.g. "acceleration") in the settings drop down box.

**Comment by piter-pit** [comment]
I had similar problem in Cura 5.0.0. Plugin works fine with Cura 5.2.1
