### ISSUE TITLE
Cool Down Speed not working (I'm using Cura 5.0.0)

### ISSUE THREAD

**Issue by Erin-Stephan** [fieldOfView/PrinterSettingsPlugin#17]
Hello, I have been doing tests with cool down speed and it is not working how it is supposed to (or how I think its supposed to). I created the ticket on the Cura github issues board [HERE](https://github.com/Ultimaker/Cura/issues/13343) but then realized its in this plugin. Basically I changed the cooling rate and part size and every time, the final print temperature is being triggered at the beginning of every other layer of infill. Same corner every time no matter what cooling rate or part size. 
![image](https://user-images.githubusercontent.com/105749971/191609154-67938204-5202-4baa-86d6-ee6eb27a0a3a.png)

**Comment by fieldOfView** [comment]
Sorry to point you straight back to Cura, but all this plugin does is making "hidden" settings visible/usable. The actual functionality of the settings is not provided by this plugin.
