### ISSUE TITLE
"Printer Settings" Sidebar disappears when loading a project

### ISSUE THREAD

**Issue by SteveDC2** [fieldOfView/PrinterSettingsPlugin#2]
I saved a project before installing the plugin and if I now open that project the "printer settings" category disappears.

Is this a bug or is there something I need to do to have "printer settings' appear in the settings when loading a project?

This is with Cura 3.5. I will try older versions when I get a chance.

**Comment by fieldOfView** [comment]
Could you test this prerelease version of th "Printer Settings" plugin?
http://files.fieldofview.com/cura/PrinterSettingsPlugin-v5.0.0-2018-11-16T14_28_49Z.curapackage
Just drop the file into the Cura window, and restart Cura.
